name: "Action Play"
description: "Run test with parameter"

inputs:
  TEST_PARAM:
    description: "Test Param"
    required: false
    default: ""
  github_token:
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

